apiVersion: v1
kind: ConfigMap
metadata:
  name: foodloop-config
  namespace: foodloop
data:
  PORT_GATEWAY: "4000"
  PORT_AUTH: "4001"
  PORT_CORE: "4002"
  PORT_AI: "5000"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  CORE_SERVICE_URL: "http://core-service:4002"
  AI_SERVICE_URL: "http://ai-service:5000"
  CLIENT_URL: "http://localhost:5173"
  JWT_EXPIRES_IN: "24h"
  GROQ_MODEL: "qwen/qwen3.6-27b"
